#ifndef CPP4_3DVIEWER_V2_2_SRC_S21_VIEW_S21_SETTINGS_H_
#define CPP4_3DVIEWER_V2_2_SRC_S21_VIEW_S21_SETTINGS_H_

#define ORGANIZATION_NAME "21_school"
#define ORGANIZATION_DOMAIN "www.21_school.ru"
#define APPLICATION_NAME "CPP4_3DViewer_v2.0"

#include <QSettings>

#endif  // CPP4_3DVIEWER_V2_2_SRC_S21_VIEW_S21_SETTINGS_H_
